services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/caddy-data:/data
      - /srv/caddy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-static:/srv/static
    restart: unless-stopped
    networks:
      - external_network
      - internal_services

networks:
  external_network:
    external: true
  internal_services:
    external: true

