version: "3.8"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    networks:
      - external_network
    volumes:
      - ./cloudflared:/etc/cloudflared
networks:
  external_network:
    external: true

